version: '3.8'
services:
  db:
    image: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'lamp'
      MYSQL_PASSWORD: 'lamp'
      MYSQL_ROOT_PASSWORD: 'lamp'